version: "3.9"

services:
  app:
    build: ./infra/php
    volumes:
      - ./src:/var/www
    depends_on:
      - db

  web:
    image: nginx:1.20-alpine
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www
    ports:
      - "8080:80"
    depends_on:
      - app

  db:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: phper
      MYSQL_PASSWORD: secret
      TZ: Asia/Tokyo
    ports:
      - "33060:3306"   # クライアントツールでローカル接続したい場合
    volumes:
      - db-data:/var/lib/mysql
  e2e:
    build:
      context: .
      dockerfile: infra/playwright/Dockerfile
    volumes:
      - .:/e2e
    depends_on:
      - web        
volumes:
  db-data:
